<?php


/*

@say3dd - Seeded the database with products for the website

*/

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // seed products, columns are: laptop_name, price, RAM, processor, GPU, image_path, brand

        DB::table('products')->insert([

            [
                'brand' => 'MSI',
                'product_name' => 'MSI Titan GT77 HX 13V',
                'product_description' => 'Name: MSI Titan GT77 HX 13V, RAM: 128 GB, Processor: 13th Gen Intel Core i9-13980HX, GPU: GeForce RTX 4090, Display: 17.3" UHD (3840x2160) 120Hz IPS-Level, Memory: 128GB DDR5, Storage: 2TB NVMe SSD, Colour: Blue',
                'category' => 'Laptop',
                'price' => 3362.99,
                'images' => 'assets/laptop_images/MSI Titan GT77 HX 13V/msi_Titan_GT77_HX_13V.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],

            [
                'brand' => 'Intel',
                'product_name' => 'Medion Erazer X20',
                'product_description' => 'Name: Intel Medion Eraser X20, RAM: 32 GB, Processor: 13th Gen Intel Core i9-13980HX,  GPU: GeForce RTX 4070, Display: 17.3" FHD (1920x1080) 144Hz IPS-Level, Memory: 32GB DDR4, Storage: 1TB NVMe SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 3262.99,
                'images' => 'assets/laptop_images/Medion Erazer X20/medion_erazer_X20.webp',
                'stock' => 14,
                'created_at' => now(),

            ],
            [
                'brand' => 'Asus',
                'product_name' => 'Asus ROG Strix G16 G614',
                'product_description' => 'Name: Asus ROG Strix G16 G614, RAM: 128 GB, Processor: 13th Gen Intel Core i9-13980HX, GPU: GeForce RTX 4090, Display: 16" WQXGA (2560x1600) 165Hz IPS-Level, Memory: 128GB DDR5 , Storage: 2TB NVMe SSD, Colour: Grey',
                'category' => 'Laptop',
                'price' => 3262.99,
                'images' => 'assets/laptop_images/Asus ROG Strix G16 G614/asus_ROG_Strix_G16_G614.jpg',
                'stock' => 12,
                'created_at' => now(),
            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Alienware M18',
                'product_description' => 'Name: Alienware M18, RAM: 32 GB, Processor: 13th Gen Intel Core i7-13700HX, GPU: GeForce RTX 4080, Display: 18" QHD (2560x1440) 165Hz ComfortView Plus, Memory: 32GB DDR5, Storage: 2TB (2x 1TB NVMe SSD RAID 0), Colour: Silver',
                'category' => 'Laptop',
                'price' => 2729.00,
                'images' => 'assets/laptop_images/Alienware M18/alienware-m18.jpg',
                'stock' => 16,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer Blade 14',
                'product_description' => 'Name: Razer Blade 14, RAM: 16 GB, Processor: AMD Ryzen 9 7940HS, GPU: GeForce RTX 4090, Display: 14" QHD (2560x1440) 165Hz IPS-Level, Memory: 16GB DDR5, Storage: 1TB NVMe SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 2099.99,
                'images' => 'assets/laptop_images/Razer Blade 14/razer_blade_14.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Lenovo',
                'product_name' => 'Lenovo Legion Pro 7i Gen 8',
                'product_description' => 'Name: Lenovo Legion Pro 7i Gen 8, RAM: 16 GB, Processor: 13th Gen Intel Core i7-13700HX, GPU: GeForce RTX 4070, Display:  16" WQXGA (2560x1600) 165Hz HDR 400 Dolby Vision, Memory: 16GB DDR5, Storage: 1TB NVMe SSD, Colour: Grey',
                'category' => 'Laptop',
                'price' => 1799.50,
                'images' => 'assets/laptop_images/Lenovo Legion Pro 7i Gen 8/lenovo_legion_pro.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS Zephyrus M16',
                'product_description' => 'Name: ASUS Zephyrus M16, RAM: 32 GB, Processor: 13th Gen Intel Core i9-13980HX, GPU: GeForce RTX 4080, Display: 16" WQXGA (2560x1600) 165Hz IPS-Level Pantone Validated, Memory: 32GB DDR5, Storage: 1TB NVMe SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 2599.99,
                'images' => 'assets/laptop_images/Asus Zephyrus M16/ASUS ZEPHYRUS.JPG',
                'stock' => 22,
                'created_at' => now(),
            ],
            [
                'brand' => 'ACER',
                'product_name' => 'ACER Predator 21 X',
                'product_description' => 'Name: ACER Predator 21 X, RAM: 64 GB, Processor: 13th Gen Intel Core i9-13980HX, GPU: GeForce RTX 4090, Display: 21" WFHD (2560x1080) 120Hz IPS Curved, Memory: 64GB DDR4, Storage: 2TB NVMe SSD + 2TB HDD, Colour: Black',
                'category' => 'Laptop',
                'price' => 2899.99,
                'images' => 'assets/laptop_images/ACER Predator 21 X/acer_predator_21.jpg',
                'stock' => 19,
                'created_at' => now(),
            ],
            [
                'brand' => 'Acer',
                'product_name' => 'Acer Predator Helios Neo 16',
                'product_description' => 'Name: Acer Predator Helios Neo 16, RAM: 16 GB, Processor: 13th Gen Intel Core i7, GPU: GeForce RTX 4070, Display:  16" WQXGA (2560x1600) 165Hz IPS-Level , Memory: 16GB DDR5, Storage: 1TB SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 1399.00,
                'images' => 'assets/laptop_images/ACER Predator Helios/acer_predator_helios_neo16.jpg',
                'stock' => 9,
                'created_at' => now(),
            ],

            [
                'brand' => 'Lenovo',
                'product_name' => 'Lenovo Legion Slim 5',
                'product_description' => 'Name: Lenovo Legion Slim 5, RAM: 16 GB, Processor: AMD Ryzen 7 7840HS, GPU: GeForce RTX 4060, Display: 15.6" FHD (1920x1080) 165Hz IPS-Level, Memory: 16GB DDR4, Storage: 512GB NVMe SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 1199.00,
                'images' => 'assets/laptop_images/Lenovo Legion Slim 5/lenovo_legion_slim_5.jpg',
                'stock' => 7,
                'created_at' => now(),
            ],
            [
                'brand' => 'Asus',
                'product_name' => 'ASUS TUF Gaming A15',
                'product_description' => 'Name: ASUS TUF Gaming A15, RAM: 16 GB, Processor: AMD Ryzen 9 7940HS, GPU: GeForce RTX 4070, Display: 15.6" FHD (1920x1080) 144Hz Adaptive-Sync, Memory: 16GB DDR5, Storage: 512GB NVMe SSD, Colour: Black',
                'category' => 'Laptop',
                'price' => 1299.00,
                'images' => 'assets/laptop_images/Asus TUF Gaming A15/asus_tuf_gaming_a15.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Asus',
                'product_name' => 'Asus ROG Zephyrus Duo',
                'product_description' => 'Name: Asus ROG Zephyrus Duo, RAM: 64 GB, Processor: AMD Ryzen 9 7945HX, GPU: GeForce RTX 4090, Display: 15.6" 4K UHD (3840x2160) 120Hz main display & 14.1" (3840x1100) touch display, Memory: 64GB DDR5, Storage: 4TB (2x 2TB NVMe SSD RAID 0), Colour: Blue',
                'category' => 'Laptop',
                'price' => 4799.00,
                'images' => 'assets/laptop_images/Asus ROG Zephyrus Duo/asus_rog_zephyrus_duo.jpg',
                'stock' => 18,
                'created_at' => now(),
            ],
            [
              'brand' => 'Razer',
              'product_name' => 'Razer Blade 18',
                'product_description' =>'Name: Razer Blade 18, RAM: 64 GB, Processor: Intel Core i9-13980HX, GPU: GeForce RTX 4070, Display: 18" QHD+ 240 Hz 16:10 (2560 x 1600), Memory: 16 GB DDR5-5600MHz, Storage: 1 TB SSD (M.2 NVMe PCIe 4.0 x4), Colour: Black',
                'category' => 'Laptop' ,
                'price' => 2699.99,
                'images' => 'assets/laptop_images/Razer Blade 18/razer-blade.jpg',
                'stock' => 5,
                'created_at' => now(),

            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Dell G15 Gaming',
                'product_description' => 'Name: Dell G15 Gaming Laptop, RAM: 64 GB, Processor: Intel Core i7-10870H, GPU: GeForce RTX 3050, Display: 15.6-inch FHD non-touchscreen, Memory: 16 GB: 2 x 8 GB DDR5 4800 MT/s, Storage: 512 GB M.2 PCIe NVMe SSD, Colour: Grey',
                'category' => 'Laptop' ,
                 'price' => 800.00,
                'images' => 'assets/laptop_images/Dell G15/dell-g15.jpg',
                'stock' => 8,
                'created_at' => now(),

            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Alienware x16 R2',
                'product_description' => 'Name: Alienware x16 R2, RAM: 32 GB, Processor: Intel Core Ultra 7, GPU: GeForce RTX 4060, Display: 16.0" QHD+ (2560 x 1600) 240Hz 3ms 100% DCI-P3 ComfortView Plus, Memory: 32 GB, Storage: 1TB SSD, Colour: Silver',
                'category' => 'Laptop' ,
                 'price' => 2499.00 ,
                'images' => 'assets/laptop_images/Alienware X16/x16-r2.jpeg',
                'stock' => 5 ,
                'created_at' => now(),

            ],
            [
                'brand' => 'MSI',
                'product_name' => 'MSI Raider GE78',
                'product_description' => 'Name: MSI Raider G378, RAM: 16 GB, Processor: Intel Core i7-12650H, GPU: GeForce RTX 4060, Display: 15.6- inch IPS LCD, Memory: 32 GB, Storage: 512 GB SSD, Colour: Black',
                'category' => 'Laptop',
                 'price' => 900.99 ,
                'images' => 'assets/laptop_images/MSI Raider GE78/msi-raider-ge.jpg',
                'stock' => 10,
                'created_at' => now(),

            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech MX Master 3',
                'product_description' => 'Name: Logitech MX Master 3, DPI: 14000, Connectivity: Wireless, Battery-Life: 70 Hours, Colour: Grey',
                'category' => 'Mouse',
                'price' => 99.99,
                'images' => 'assets/Mouse_images/mx_master_3.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer DeathAdder V2',
                'product_description' => 'Name: Razer DeathAdder V2, DPI: 20000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 69.99,
                'images' => 'assets/Mouse_images/razer_deathadder_v2.jpeg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair Ironclaw RGB',
                'product_description' => 'Name: Corsair Ironclaw RGB, DPI: 18000, Connectivity: Wireless, Battery-Life: 50 Hours, Colour: Black',
                'category' => 'Mouse',
                'price' => 79.99,
                'images' => 'assets/Mouse_images/corsair_ironclaw_rgb.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech PRO X SUPERLIGHT 2',
                'product_description' => 'Name: PRO X SUPERLIGHT 2, DPI: 32000, Connectivity: Wireless, Battery-Life: 95 Hours, Colour: Black',
                'category' => 'Mouse',
                'price' => 149.00,
                'images' => 'assets/Mouse_images/superlight_logitech.jpg',
                'stock' => 8 ,
                'created_at' => now(),

            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech G502 Hero',
                'product_description' => 'Name: Logitech G502 Hero, DPI: 32000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 49.99,
                'images' => 'assets/Mouse_images/g502-log.jpg',
                'stock' => 12 ,
                'created_at' => now(),

],
            [
                'brand' => 'HyperX',
                'product_name' => 'HyperX Pulse FPS pro',
                'product_description' => 'Name:Pulse FPS pro, DPI: 16000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 49.99,
                'images' => 'assets/Mouse_images/pulsefire_pro.jpg',
                'stock' => 10,
                'created_at' => now(),

            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer DeathAdder Elite',
                'product_description' => 'Name:Razer DeathAdder Elite, DPI: 16000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 25.99,
                'images' => 'assets/Mouse_images/DeathAdder_elite.jpg',
                'stock' => 10,
                'created_at' => now(),

            ],
            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Rival 600',
                'product_description' => 'Name: SteelSeries Rival 600, DPI: 14000, Connectivity: Wired, Colour: White',
                'category' => 'Mouse',
                'price' => 55.99,
                'images' => 'assets/Mouse_images/rival_600.jpg',
                'stock' => 10,
                'created_at' => now(),

            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair Harpoon RGB PRO',
                'product_description' => 'Name: Corsair Harpoon RGB PRO, DPI: 16000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 35.99,
                'images' => 'assets/Mouse_images/Corsair_Harpoon.jpg',
                'stock' => 10,
                'created_at' => now(),

            ],
            [
                'brand' => 'Asus',
                'product_name' => 'Asus ROG Keris Aimpoint',
                'product_description' => 'Name: Asus ROG Keris Aimpoint, DPI: 16000, Connectivity: Wireless, Battery-Life: 60 Hours, Colour: White',
                'category' => 'Mouse',
                'price' => 89.99,
                'images' => 'assets/Mouse_images/keris_aimpoint.jpg',
                'stock' => 7,
                'created_at' => now(),

            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer Basilisk Ultimate',
                'product_description' => 'Name: Razer Basilisk Ultimate, DPI: 20000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 149.99,
                'images' => 'assets/Mouse_images/basilisk.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer Viper Ultimate',
                'product_description' => 'Name: Razer Viper Ultimate, DPI: 20000, Connectivity: Wireless, Battery-Life: 70 Hours, Colour: Black',
                'category' => 'Mouse',
                'price' => 169.99,
                'images' => 'assets/Mouse_images/razer-ultimate.jpeg',
                'stock' => 15,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS ROG Gladius II',
                'product_description' => 'Name: ASUS ROG Gladius II, DPI: 14000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 79.99,
                'images' => 'assets/Mouse_images/rog-gladius.jpg',
                'stock' => 20,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair Dark Core RGB Pro SE',
                'product_description' => 'Name: Corsair Dark Core RGB Pro SE, DPI: 18000, Connectivity: Wireless, Battery-Life: 50 Hours, Colour: Black',
                'category' => 'Mouse',
                'price' => 99.99,
                'images' => 'assets/Mouse_images/dark-core.jpg',
                'stock' => 12,
                'created_at' => now(),
            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech G903 Lightspeed',
                'product_description' => 'Name: Logitech G903 Lightspeed, DPI: 16000, Connectivity: Wireless, Battery-Life: 70 Hours, Colour: Black',
                'category' => 'Mouse',
                'price' => 129.99,
                'images' => 'assets/Mouse_images/lightspeed-logi.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Sensei 310',
                'product_description' => 'Name: SteelSeries Sensei 310, DPI: 14000, Connectivity: Wired, Colour: Black',
                'category' => 'Mouse',
                'price' => 59.99,
                'images' => 'assets/Mouse_images/sensei-310.jpg',
                'stock' => 15,
                'created_at' => now(),
            ],


            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Apex Pro',
                'product_description' => 'Name: SteelSeries Apex Pro, Switches: Red, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 199.99,
                'images' => 'assets/Keyboard_Images/apex-pro.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair K95 RGB Platinum',
                'product_description' => 'Name: Corsair K95 RGB Platinum, Switches: Red, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 169.99,
                'images' => 'assets/Keyboard_Images/corsair-platinum.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer Cynosa Chroma',
                'product_description' => 'Name: Razer Cynosa Chroma, Switches: Membrane, Connectivity: Wired, Keyboard-Type: Membrane, Colour: Black',
                'category' => 'Keyboard',
                'price' => 59.99,
                'images' => 'assets/Keyboard_Images/chnosav2.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Apex 3',
                'product_description' => 'Name: SteelSeries Apex 3, Switches: Membrane, Connectivity: Wired, Keyboard-Type: Membrane, Colour: Black',
                'category' => 'Keyboard',
                'price' => 69.99,
                'images' => 'assets/Keyboard_Images/apex3-tkl.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer Huntsman Elite',
                'product_description' => 'Name: Razer Huntsman Elite, Switches: Blue, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 199.99,
                'images' => 'assets/Keyboard_Images/razerhuntsman.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech G Pro X',
                'product_description' => 'Name: Logitech G Pro X, Switches: Blue, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: White',
                'category' => 'Keyboard',
                'price' => 149.99,
                'images' => 'assets/Keyboard_Images/logi-g-pro.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS ROG Strix Scope',
                'product_description' => 'Name: ASUS ROG Strix Scope, Switches: Red, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: White',
                'category' => 'Keyboard',
                'price' => 129.99,
                'images' => 'assets/Keyboard_Images/rog-strix.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Cooler Master',
                'product_name' => 'Cooler Master CK550',
                'product_description' => 'Name: Cooler Master CK550, Switches: Red, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 79.99,
                'images' => 'assets/Keyboard_Images/ck550-rg.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair K70 RGB MK.2',
                'product_description' => 'Name: Corsair K70 RGB MK.2, Switches: Cherry MX Speed, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 159.99,
                'images' => 'assets/Keyboard_Images/corsair k70.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Apex 7',
                'product_description' => 'Name: SteelSeries Apex 7, Switches: Cherry MX Red, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 149.99,
                'images' => 'assets/Keyboard_Images/apex-7.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech G915 LIGHTSPEED',
                'product_description' => 'Name: Logitech G915 LIGHTSPEED, Switches: Blue, Connectivity: Wireless, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 249.99,
                'images' => 'assets/Keyboard_Images/logi-g915.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Redragon',
                'product_name' => 'Redragon K552',
                'product_description' => 'Name: Redragon K552, Switches: Blue, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 39.99,
                'images' => 'assets/Keyboard_Images/reddragon.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer BlackWidow V3 Pro',
                'product_description' => 'Name: Razer BlackWidow V3 Pro, Switches: Red, Connectivity: Wireless, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 229.99,
                'images' => 'assets/Keyboard_Images/razer v3.webp',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair K63',
                'product_description' => 'Name: Corsair K63, Switches: Cherry MX Red, Connectivity: Wireless, Keyboard-Type: Mechanical, Colour: Blue',
                'category' => 'Keyboard',
                'price' => 109.99,
                'images' => 'assets/Keyboard_Images/corsair-k63.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Ducky',
                'product_name' => 'Ducky One 2 Mini RGB',
                'product_description' => 'Name: Ducky One 2 Mini RGB, Switches: Blue, Connectivity: Wired, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 129.99,
                'images' => 'assets/Keyboard_Images/duckyone.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Anne Pro',
                'product_name' => 'Anne Pro 2 RGB',
                'product_description' => 'Name: Anne Pro 2 RGB, Switches: Blue, Connectivity: Wireless, Keyboard-Type: Mechanical, Colour: Black',
                'category' => 'Keyboard',
                'price' => 99.99,
                'images' => 'assets/Keyboard_Images/annepro 2.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
                        [
                'brand' => 'LG',
                'product_name' => 'LG UltraGear 27GL850-B',
                'product_description' => 'Name: LG UltraGear 27GL850-B, Screen-Size: 27", Refresh-Rate: 144Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 399.99,
                'images' => 'assets/Monitor_images/lg- ultreagear.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Dell UltraSharp UP3218K',
                'product_description' => 'Name: Dell UltraSharp UP3218K, Screen-Size: 32", Refresh-Rate: 60Hz, Response-Time: 8ms, Colour: White',
                'category' => 'Monitor',
                'price' => 399.99,
                'images' => 'assets/Monitor_images/dell-ultrasharp32.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS ROG Swift PG279Q',
                'product_description' => 'Name: ASUS ROG Swift PG279Q, Screen-Size: 27", Refresh-Rate: 165Hz, Response-Time: 4ms, Colour: Dark Grey',
                'category' => 'Monitor',
                'price' => 699.99,
                'images' => 'assets/Monitor_images/rog-swift pg.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Dell S-Series S27',
                'product_description' => 'Name: Dell S-Series S2719DGF, Screen-Size: 27", Refresh-Rate: 155Hz, Response-Time: 1ms, Colour: Dark Grey',
                'category' => 'Monitor',
                'price' => 299.99,
                'images' => 'assets/Monitor_images/dell S-Series 27.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Dell',
                'product_name' => 'Dell S3220DGF',
                'product_description' => 'Name: Dell S3220DGF, Screen-Size: 32", Refresh-Rate: 165Hz, Response-Time: 4ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 499.99,
                'images' => 'assets/Monitor_images/Dell S320.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Acer',
                'product_name' => 'Acer Nitro XV273K',
                'product_description' => 'Name: Acer Nitro XV273K, Screen-Size: 27", Refresh-Rate: 144Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 699.99,
                'images' => 'assets/Monitor_images/Nitro-monitor.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Acer',
                'product_name' => 'Acer Predator XB27',
                'product_description' => 'Name: Acer Predator XB27 series, Screen-Size: 27", Refresh-Rate: 144Hz, Response-Time: 4ms, Colour: Red',
                'category' => 'Monitor',
                'price' => 599.99,
                'images' => 'assets/Monitor_images/Acer Pred-xb.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'HP',
                'product_name' => 'HP Omen X 25',
                'product_description' => 'Name: HP Omen X 25, Screen-Size: 24.5", Refresh-Rate: 240Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 329.99,
                'images' => 'assets/Monitor_images/omenx25.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'MSI',
                'product_name' => 'MSI Optix MAG271CQR',
                'product_description' => 'Name: MSI Optix MAG271CQR, Screen-Size: 27", Refresh-Rate: 144Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 379.99,
                'images' => 'assets/Monitor_images/mag27.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS TUF Gaming VG27AQ',
                'product_description' => 'Name: ASUS TUF Gaming VG27AQ, Screen-Size: 27", Refresh-Rate: 165Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 399.99,
                'images' => 'assets/Monitor_images/tuf gaming vg.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'BenQ',
                'product_name' => 'BenQ EX2780Q',
                'product_description' => 'Name: BenQ EX2780Q, Screen-Size: 27", Refresh-Rate: 144Hz, Response-Time: 5ms, Colour: Dark Grey',
                'category' => 'Monitor',
                'price' => 499.99,
                'images' => 'assets/Monitor_images/benq ex27.webp',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'HP',
                'product_name' => 'HP Omen X 27',
                'product_description' => 'Name: HP Omen X 27, Screen-Size: 27", Refresh-Rate: 240Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 599.99,
                'images' => 'assets/Monitor_images/omenx27.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Acer',
                'product_name' => 'Acer Predator XB3',
                'product_description' => 'Name: Acer Predator XB253QGX, Screen-Size: 24.5", Refresh-Rate: 240Hz, Response-Time: 1ms, Colour: Black',
                'category' => 'Monitor',
                'price' => 349.99,
                'images' => 'assets/Monitor_images/pred xb3.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Sony',
                'product_name' => 'Sony XM4s',
                'product_description' => 'Name: Sony Headset1, Connectivity: Wireless, Colour: White',
                'category' => 'Headset',
                'price' => 249.99,
                'images' => 'assets/Headset_images/sony xm4s.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'SteelSeries',
                'product_name' => 'SteelSeries Arctis 7',
                'product_description' => 'Name: SteelSeries Arctis 7, Connectivity: Wireless, Colour: White',
                'category' => 'Headset',
                'price' => 149.99,
                'images' => 'assets/Headset_images/arctis-7.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'HyperX',
                'product_name' => 'HyperX Cloud II',
                'product_description' => 'Name: HyperX Cloud II, Connectivity: Wired, Colour: Silver',
                'category' => 'Headset',
                'price' => 99.99,
                'images' => 'assets/Headset_images/Hyperx-cloudii.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Razer',
                'product_name' => 'Razer BlackShark V2',
                'product_description' => 'Name: Razer BlackShark V2, Connectivity: Wired, Colour: Black',
                'category' => 'Headset',
                'price' => 99.99,
                'images' => 'assets/Headset_images/razer-blackv2.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Logitech',
                'product_name' => 'Logitech G Pro X Wireless',
                'product_description' => 'Name: Logitech G Pro X Wireless, Connectivity: Wireless, Colour: Black',
                'category' => 'Headset',
                'price' => 199.99,
                'images' => 'assets/Headset_images/prox2.png',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Corsair',
                'product_name' => 'Corsair Void RGB Elite Wireless',
                'product_description' => 'Name: Corsair Void RGB Elite Wireless, Connectivity: Wireless, Colour: White',
                'category' => 'Headset',
                'price' => 129.99,
                'images' => 'assets/Headset_images/corsair-voidelite.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Astro',
                'product_name' => 'Astro A50 Wireless',
                'product_description' => 'Name: Astro A50 Wireless, Connectivity: Wireless, Colour: Green',
                'category' => 'Headset',
                'price' => 299.99,
                'images' => 'assets/Headset_images/astro-green.jpeg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Sennheiser',
                'product_name' => 'Sennheiser Game One',
                'product_description' => 'Name: Sennheiser Game One, Connectivity: Wired, Colour: White',
                'category' => 'Headset',
                'price' => 169.99,
                'images' => 'assets/Headset_images/gameone.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'ASUS',
                'product_name' => 'ASUS ROG Theta 7.1',
                'product_description' => 'Name: ASUS ROG Theta 7.1, Connectivity: Wired, Colour: Black',
                'category' => 'Headset',
                'price' => 299.99,
                'images' => 'assets/Headset_images/theta.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Turtle Beach',
                'product_name' => 'Turtle Beach Stealth 600 Gen 2',
                'product_description' => 'Name: Turtle Beach Stealth 600 Gen 2, Connectivity: Wireless, Colour: Black',
                'category' => 'Headset',
                'price' => 99.99,
                'images' => 'assets/Headset_images/turtlebeach-stealth.jpeg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'HyperX',
                'product_name' => 'HyperX Cloud Flight Wireless',
                'product_description' => 'Name: HyperX Cloud Flight Wireless, Connectivity: Wireless, Colour: Black',
                'category' => 'Headset',
                'price' => 159.99,
                'images' => 'assets/Headset_images/hyperx-cloud.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],
            [
                'brand' => 'Sennheiser',
                'product_name' => 'Sennheiser GSP 600',
                'product_description' => 'Name: Sennheiser GSP 600, Connectivity: Wired, Colour: Black',
                'category' => 'Headset',
                'price' => 249.99,
                'images' => 'assets/Headset_images/sennheiser gsp.jpg',
                'stock' => 10,
                'created_at' => now(),
            ],

        ]);

        /*new product lists goes here.
Simply open square bracket (array) and add a comma in the end of the array. */




    }
}

